# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            tech blog
tagline:          'Musings on Computer Science'
#description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
description:	   Musings and daily applications of Machine Learning
url:              http://beniz.github.io/
baseurl:          http://beniz.github.io/hyde/

author:
  name:           'Emmanuel Benazera'
  url:            https://twitter.com/pilooch

paginate:         5

# Custom vars
#version:          0.1

github:		  
  repo:           https://github.com/beniz/
